micronaut:
  server:
    port: 8080
datasources:
  default:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

meta-server:
  edit.secret: "foo"
  dbip.api.key: "bar"
  module:
    metadataFileNames:
      - module.json
      - module.txt